apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring

resources:
- httproute-grant.yaml
- monitoring-grafana.yaml
- grafana-oauth-external-secret.yaml
- discord-webhook-external-secret.yaml
- vmalertmanager-config.yaml
- control-plane-monitoring.yaml
- control-plane-static-scrapes.yaml
- etcd-metrics.yaml
- loki-datasource.yaml
- hardware-monitoring-dashboard.yaml