apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring

resources:
- httproute-grant.yaml
- monitoring-grafana.yaml
- legacyscrape.yaml
- grafana-oauth-external-secret.yaml