apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openclaw

resources:
- serviceaccount.yaml
- configmap.yaml
- external-secret.yaml
- oauth2-proxy-secret.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- httproute-grant.yaml
- network-policy.yaml
