apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: n8n

resources:
- httproute-grant.yaml
- n8n-claim0-persistentvolumeclaim.yaml
- n8n-deployment.yaml
- n8n-service.yaml
- oauth2-proxy-secret.yaml
- postgres-claim0-persistentvolumeclaim.yaml
- postgres-configmap.yaml
- postgres-deployment.yaml
- postgres-external-secret.yaml
- postgres-service.yaml