config:
  existingSecret: n8n-oauth2-proxy-secrets

extraArgs:
  provider: oidc
  oidc-issuer-url: "https://authentik.dhlabs.org/application/o/n8n/"  
  redirect-url: "https://n8n.dhlabs.org/oauth2/callback"
  provider-display-name: "Authentik"
  skip-provider-button: "true"
  cookie-secure: "true"
  email-domain: "*"
  pass-access-token: "true"
  set-xauthrequest: "true"
  skip-auth-regex: "^/oauth2/.*"
  upstream: "http://n8n:5678"
