apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: home-assistant

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount-token-secret.yaml
- serviceaccount.yaml