apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps

resources:
  - monitoring.yaml
  - argocd.yaml
  - argocd-image-updater.yaml
  - cert-manager.yaml
  - gateway-api.yaml
  - ingress.yaml
  - promtail.yaml
  - cilium.yaml
  - loki.yaml
  - external-dns.yaml
  - minio.yaml
  - cyberchef.yaml
  - metrics-server.yaml
  - home-assistant.yaml
  #- awx.yaml
  - authentik.yaml
  - harbor.yaml
  - 1password.yaml
  - external-secrets.yaml
  - dayz.yaml
  - crossplane.yaml
  - kmcp.yaml
  - k8s-workshop.yaml
  - flatcar.yaml
  - ollama.yaml
  - elasticsearch-rag.yaml
  - wonderful-rag.yaml
  - strimzi.yaml
  - postgres.yaml