apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: elasticsearch-rag

namespace: elasticsearch-rag

resources:
  - namespace.yaml
  - elasticsearch-statefulset.yaml
  - rag-pipeline-deployment.yaml
  - configmap.yaml

