---
- name: Get kubeadm join command from control plane
  hosts: control_plane
  become: true
  tasks:
    - name: Get kubeadm join command
      command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Show join command
      debug:
        var: join_cmd.stdout
