---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kmcp-kubeconfig
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kubeconfig
        metadataPolicy: None
      secretKey: config
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: dhlabs
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
