apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kmcp

resources:
- azure-devops-mcp.yaml
- azure-devops-secret.yaml
- httproute-grant.yaml
- kubeconfig-secret.yaml
- mcp-test.yaml
- rbac.yaml