apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress

resources:
- ingress-gw.yaml
- argocd-httproute.yaml
- grafana-httproute.yaml
- cyberchef-httproute.yaml
- minio-httproute.yaml
#- awx-httproute.yaml
- authentik-httproute.yaml
- harbor-httproute.yaml
- kmcp-httproute.yaml