apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: k8s-workshop

namespace: k8s-workshop

resources:
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/httproute-grant.yaml
