apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop
  labels:
    app: k8s-workshop
spec:
  type: ClusterIP
  selector:
    app: k8s-workshop
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
