apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dayz

resources:
- configmap.yaml
- cronjob.yaml
- deployment.yaml
- mod-downloader-configmap.yaml
- pvc.yaml
- rbac.yaml
- secrets.yaml
- server-passwords.yaml
- serviceaccount.yaml
- svc.yaml