nameOverride: "minio"
fullnameOverride: "minio"

mode: standalone

# Use External Secret for authentication
auth:
  rootUser: admin
  existingSecret: minio-admin-secret

persistence:
  enabled: true
  storageClass: nfs
  accessMode: ReadWriteMany
  size: 150Gi

service:
  type: ClusterIP
  port: "9000"

consoleService:
  type: ClusterIP
  port: "9001"

securityContext:
  enabled: true
  runAsUser: 65534
  runAsGroup: 100
  fsGroup: 100
  fsGroupChangePolicy: "OnRootMismatch"

metrics:
  serviceMonitor:
    enabled: true
    includeNode: true
    public: true
    namespace: minio
    interval: 60s
    scrapeTimeout: 30s

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 200m